modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="superdifficultmod"
version="0.0.5"
displayName="有趣的模组"
credits="Mcreator"
displayURL="https://gitee.com/frankrank/harmcmod"
logoFile="logo.png"
authors="frankrank"
description='''
一个让你生存等级难度倍增的模组，同时也有很多有趣的东西。由frankrank制作。
'''

[[dependencies.superdifficultmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




